services:
  app:
    init: true
    image: "${IMAGE_NAME}:${IMAGE_TAG}"
    build:
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT
        - APP_NAME
        - APP_VERSION
        - COMMIT_SHA
      tags:
        - "${IMAGE_NAME}:${IMAGE_TAG_ALIAS}"
    ports:
      - "127.0.0.1:3000:8000"
